### ISSUE TITLE
pkg-config support

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/PublicDecompWT-rpm#1]
I'd like to have pkg-config support in the rpm packages. Feel free to cherry-pick generation from https://salsa.debian.org/enrico/publicdecompwt

**Comment by brancomat** [comment]
For the time being I added a finely crafted `.pc` file as a quick-and-dirty solution, for the future I might steal the cmake approach from https://salsa.debian.org/enrico/publicdecompwt, thanks
